=== cloudgraph/cloudgraph/doclets/yworks-uml-doclet-3.0_01-jdk1.5/resources/taglet_definitions.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD for taglet definitions -->

<!ELEMENT taglet-list (taglet+)>
<!ELEMENT taglet (usage, headline)>
<!ELEMENT usage EMPTY>
<!ELEMENT headline (singular, plural*)>
<!ELEMENT singular (#PCDATA)>
<!ELEMENT plural (#PCDATA)>

<!ATTLIST taglet
          name              CDATA        #REQUIRED
	  template          CDATA        #REQUIRED
	  allowMultipleTags (true|false) #REQUIRED>
<!ATTLIST usage
          inField        (true|false) #REQUIRED
  	  inConstructor  (true|false) #REQUIRED
  	  inMethod       (true|false) #REQUIRED
  	  inOverview     (true|false) #REQUIRED
  	  inPackage      (true|false) #REQUIRED
  	  inType         (true|false) #REQUIRED
  	  isInlineTag    (true|false) #REQUIRED>

=== cloudgraph/cloudgraph/doclets/yworks-uml-doclet-3.0_01-jdk1.5/resources/taglet_definitions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE taglet-list SYSTEM "taglet_definitions.dtd">

<!--
 #
 # See taglet_definitions.dtd for valid tags and attributes
 #
 #
 # Each <taglet>-tag results in the registration of one particular taglet.
 # The value of the "name" attribute specifies the javadoc tag for the taglet.
 # The value of the "allowMultipleTags" attribute specifies if more than one
 # appearance of the javadoc tag per doc element is allowed. If not, all but
 # the first tag will be ignored.
 #
 # The <usage>-tag specifies the taglet scope as per the taglet API.
 #
 # The <singular>-tag specifies the term under which the tag comment appears
 # if only one javadoc tag or no <plural>-tag is present.
 # The optional <plural>-tag specifies the term under which the tag comment
 # appears if multiple javadoc tags are allowed and present.
 #
 #
 # In general, it is a good idea to use at least one '.' character in the
 # name of custom tags to avoid potential conflicts/overrides.
 #
-->
<taglet-list>
	<taglet name="y.complexity"
		template="simpleComment"
		allowMultipleTags="false">
		<usage inField="false"
			inConstructor="true"
			inMethod="true"
			inOverview="false"
			inPackage="false"
			inType="true"
			isInlineTag="false"/>
		<headline>
			<singular>Complexity</singular>
		</headline>
	</taglet>
	<taglet name="y.precondition"
		template="simpleComment"
		allowMultipleTags="true">
		<usage inField="false"
			inConstructor="true"
			inMethod="true"
			inOverview="false"
			inPackage="false"
			inType="true"
			isInlineTag="false"/>
		<headline>
			<singular>Precondition</singular>
			<plural>Preconditions</plural>
		</headline>
	</taglet>
	<taglet name="y.postcondition"
		template="simpleComment"
		allowMultipleTags="true">
		<usage inField="false"
			inConstructor="true"
			inMethod="true"
			inOverview="false"
			inPackage="false"
			inType="true"
			isInlineTag="false"/>
		<headline>
			<singular>Postcondition</singular>
			<plural>Postconditions</plural>
		</headline>
	</taglet>
	<taglet name="y.author"
		template="simpleList"
		allowMultipleTags="true">
		<usage inField="true"
			inConstructor="true"
			inMethod="true"
			inOverview="true"
			inPackage="true"
			inType="true"
			isInlineTag="false"/>
		<headline>
			<singular>Author</singular>
		</headline>
	</taglet>
</taglet-list>
