=== cloudgraph/cloudgraph/doclets/yworks-uml-doclet-3.0_01-jdk1.5/resources/styles/ydocstyle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.yworks.com/xml/ydocstyle"
    xmlns="http://www.yworks.com/xml/ydocstyle"
    elementFormDefault="qualified">

    <xs:simpleType name="arrowType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="circle"/>
            <xs:enumeration value="transparent_circle"/>
            <xs:enumeration value="transparent_semi_circle"/>
            <xs:enumeration value="white_circle"/>
            
            <xs:enumeration value="uml"/>
            <xs:enumeration value="none"/>
            <xs:enumeration value="short"/>
            <xs:enumeration value="standard"/>
            
            <xs:enumeration value="delta"/>
            <xs:enumeration value="white_delta"/>
            <xs:enumeration value="diamond"/>
            <xs:enumeration value="white_diamond"/>
        </xs:restriction>
    </xs:simpleType>
 
    <xs:simpleType name="colorType">
        <xs:restriction base="xs:string">
            <xs:pattern value="#[a-f0-9]{6}|#[a-f0-9]{8}|"/>
        </xs:restriction>
    </xs:simpleType>
 
    <xs:simpleType name="fontType">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*-(bold|italic|bolditalic|plain)-[1-9]*"/>
        </xs:restriction>
    </xs:simpleType>
 
    <xs:simpleType name="lineType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(dashed|dotted|line)_[1-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:attributeGroup name="edgeStyleAttributes">
        <xs:attribute
            name="source.arrow"
            type="arrowType"
            use="optional"/>
        <xs:attribute
            name="target.arrow"
            type="arrowType"
            use="optional"/>
        
        <xs:attribute
            name="line.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="line.stroke" 
            type="lineType"
            use="optional"/>

         <xs:attribute
             name="bend.style"
             use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="angled"/>
                    <xs:enumeration value="smooth"/>
                </xs:restriction>
              </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>

    <xs:attributeGroup name="nodeStyleAttributes">
        <xs:attribute
            name="shadow.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="shadow.width" 
            type="xs:byte"
            use="optional"/>
        <xs:attribute
            name="shadow.height" 
            type="xs:byte"
            use="optional"/>
        <xs:attribute
            name="shadow.style"
            use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="solid"/>
                    <xs:enumeration value="soft"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute
            name="line.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="line.stroke"
            type="lineType"
            use="optional"/>
        
        <xs:attribute name="header.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="header.gradient.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="header.style"
            use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="default"/>
                    <xs:enumeration value="iconified"/>
                    <xs:enumeration value="span_section"/>
                    <xs:enumeration value="left_tab"/>
                    <xs:enumeration value="center_tab"/>
                    <xs:enumeration value="right_tab"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute
            name="icon.style"
            use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="vectorgraphics"/>
                    <xs:enumeration value="ascii"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute
            name="separator.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="separator.style"
            use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="dynamic"/>
                    <xs:enumeration value="fixed"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute
            name="shape"
            use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="ellipse"/>
                    <xs:enumeration value="oval"/>
                    <xs:enumeration value="circle"/>
                    <xs:enumeration value="rectangle"/>
                    <xs:enumeration value="triangle"/>
                    <xs:enumeration value="parallelogram"/>
                    <xs:enumeration value="hexagon"/>
                    <xs:enumeration value="diamond"/>
                    <xs:enumeration value="octagon"/>
                    <xs:enumeration value="roundrectangle"/>
                    <xs:enumeration value="rectangle3d"/>
                    <xs:enumeration value="trapezoid"/>
                    <xs:enumeration value="trapezoid2"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute
            name="section.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="section.gradient.color"
            type="colorType"
            use="optional"/>
        
        <xs:attribute
            name="constraint.label.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="constraint.label.text"
            type="xs:string"
            use="optional"/>
        <xs:attribute
            name="constraint.label.text.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="name.label.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="name.label.text.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="stereotype.label.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="stereotype.label.text"
            type="xs:string"
            use="optional"/>
        <xs:attribute
            name="stereotype.label.text.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="type.label.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="type.label.text"
            type="xs:string"
            use="optional"/>
        <xs:attribute
            name="type.label.text.color"
            type="colorType"
            use="optional"/>

        <xs:attribute
            name="fields.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="fields.gradient.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="fields.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="fields.text.color"
            type="colorType"
            use="optional"/>
        
        <xs:attribute
            name="constructors.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="constructors.gradient.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="constructors.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="constructors.text.color"
            type="colorType"
            use="optional"/>

        <xs:attribute
            name="methods.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="methods.gradient.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="methods.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="methods.text.color"
            type="colorType"
            use="optional"/>
    </xs:attributeGroup>
 

    <xs:complexType name="nodeStyleType">
        <xs:attribute
            name="styleRef"
            type="xs:string"
            use="optional"/>
        <xs:attributeGroup ref="nodeStyleAttributes"/>
    </xs:complexType>

    <xs:element name="StyleDefinition">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="EdgeStyle">
                        <xs:complexType>
                            <xs:attribute
                                name="styleId"
                                type="xs:string"
                                use="required"/>
                            <xs:attribute
                                name="styleRef"
                                type="xs:string"
                                use="optional"/>
                            <xs:attributeGroup ref="edgeStyleAttributes"/>
                        </xs:complexType>
                    </xs:element>
                    
                    <xs:element name="NodeStyle">
                        <xs:complexType>
                            <xs:complexContent>
                                <xs:extension base="nodeStyleType">
                                    <xs:attribute
                                        name="styleId"
                                        type="xs:string"
                                        use="required"/>
                                </xs:extension>
                            </xs:complexContent>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>              
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cloudgraph/cloudgraph/doclets/yworks-uml-doclet-3.0_01-jdk1.5/resources/styles/muted-colors-style.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<StyleDefinition
 xmlns="http://www.yworks.com/xml/ydocstyle"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.yworks.com/xml/ydocstyle http://www.yworks.com/xml/schema/ydoc/1.0/ydocstyle.xsd">
  <NodeStyle
   constraint.label.font="Dialog-plain-12"
   constraint.label.text=""
   constraint.label.text.color="#000000"
   constructors.fill.color=""
   constructors.font="Dialog-plain-12"
   constructors.gradient.color=""
   constructors.text.color="#000000"
   fields.fill.color=""
   fields.font="Dialog-plain-12"
   fields.gradient.color=""
   fields.text.color="#000000"
   header.fill.color="#FFFFFF"
   header.gradient.color=""
   header.style="span_section"
   icon.style="vectorgraphics"
   line.color="#999999"
   line.stroke="line_1"
   methods.fill.color=""
   methods.font="Dialog-plain-12"
   methods.gradient.color=""
   methods.text.color="#000000"
   name.label.font="Dialog-plain-12"
   name.label.text.color="#000000"
   section.fill.color=""
   section.gradient.color=""
   separator.fill.color=""
   separator.style="fixed"
   shadow.color="#B3A691"
   shadow.height="1"
   shadow.style="solid"
   shadow.width="1"
   shape="roundrectangle"
   stereotype.label.font="Dialog-plain-12"
   stereotype.label.text=""
   stereotype.label.text.color="#000000"
   styleId="node-type"
   type.label.font="Dialog-plain-12"
   type.label.text=""
   type.label.text.color="#000000"/>
  <NodeStyle
   constructors.fill.color="#F3F3F3"
   fields.fill.color="#F3F3F3"
   line.color="#CCCCCC"
   methods.fill.color="#F3F3F3"
   separator.fill.color="#CCCCCC"
   styleId="classifier"
   styleRef="node-type"/>
  <NodeStyle
   header.fill.color="#E66E6E"
   line.color="#BD5555"
   name.label.font="Dialog-bold-14"
   section.fill.color="#F0F0F0"
   separator.style="dynamic"
   styleId="group"
   styleRef="node-type"/>
  <NodeStyle
   header.fill.color="#91B9FF"
   styleId="exception"
   styleRef="classifier"
   type.label.text="exception"/>
  <NodeStyle
   header.fill.color="#B4B4B4"
   line.color="#999999"
   name.label.font="Dialog-bold-14"
   section.fill.color="#F0F0F0"
   separator.style="dynamic"
   styleId="package"
   styleRef="node-type"/>
  <NodeStyle
   header.fill.color="#91BE91"
   styleId="annotation"
   styleRef="classifier"/>
  <NodeStyle
   name.label.font="Dialog-plain-12"
   shape="ellipse"
   styleId="annotation.compact"
   styleRef="annotation"/>
  <NodeStyle
   header.fill.color="#FAD27D"
   styleId="abstract"
   styleRef="classifier"
   type.label.text="abstract"/>
  <NodeStyle
   header.fill.color="#91B9FF"
   styleId="error"
   styleRef="classifier"
   type.label.text="error"/>
  <NodeStyle
   header.fill.color="#91B9FF"
   styleId="class"
   styleRef="classifier"
   type.label.text="class"/>
  <NodeStyle
   header.fill.color="#91B9FF"
   styleId="enum"
   styleRef="classifier"
   type.label.text="enum"/>
  <NodeStyle
   constructors.fill.color="#EBEBD7"
   fields.fill.color="#EBEBD7"
   header.fill.color="#91BE91"
   methods.fill.color="#EBEBD7"
   styleId="interface"
   styleRef="classifier"/>
  <NodeStyle
   name.label.font="Dialog-plain-12"
   styleId="error.compact"
   styleRef="error"/>
  <NodeStyle
   name.label.font="Dialog-bold-16"
   stereotype.label.text="«annotation»"
   styleId="annotation.detailed"
   styleRef="annotation"/>
  <NodeStyle
   name.label.font="Dialog-plain-12"
   styleId="exception.compact"
   styleRef="exception"/>
  <NodeStyle
   name.label.font="Dialog-bold-16"
   styleId="exception.detailed"
   styleRef="exception"/>
  <NodeStyle
   name.label.font="Dialog-plain-12"
   styleId="enum.compact"
   styleRef="enum"/>
  <NodeStyle
   name.label.font="Dialog-bold-16"
   stereotype.label.text="«interface»"
   styleId="interface.detailed"
   styleRef="interface"/>
  <NodeStyle
    name.label.font="Dialog-plain-12"
   styleId="abstract.compact"
   styleRef="abstract"/>
  <NodeStyle
   methods.fill.color="#EBEDFF"
   name.label.font="Dialog-plain-12"
   section.fill.color="#EBEBFF"
   styleId="class.compact"
   styleRef="class"/>
  <NodeStyle
   constructors.fill.color="#EBEBF5"
   fields.fill.color="#EBEBF5"
   methods.fill.color="#EBEBF5"
   name.label.font="Dialog-bold-16"
   styleId="class.detailed"
   styleRef="class"/>
  <NodeStyle
   name.label.font="Dialog-bold-16"
   styleId="error.detailed"
   styleRef="error"/>
  <NodeStyle
   constructors.fill.color="#FAF0D2"
   fields.fill.color="#FAF0D2"
   header.fill.color="#FAD27D"
   methods.fill.color="#FAF0D2"
   name.label.font="Dialog-bold-16"
   styleId="abstract.detailed"
   styleRef="abstract"/>
  <NodeStyle
   name.label.font="Dialog-bold-16"
   styleId="enum.detailed"
   styleRef="enum"/>
  <NodeStyle
   name.label.font="Dialog-plain-12"
   shape="ellipse"
   styleId="interface.compact"
   styleRef="interface"/>
  <EdgeStyle
   bend.style="angled"
   line.color="#000000"
   line.stroke="dashed_1"
   source.arrow="none"
   styleId="dependency"
   target.arrow="UML:Wedge"/>
  <EdgeStyle
   bend.style="angled"
   line.color="#000000"
   line.stroke="dashed_2"
   source.arrow="none"
   styleId="realization"
   target.arrow="white_delta"/>
  <EdgeStyle
   bend.style="angled"
   line.color="#000000"
   line.stroke="dashed_1"
   source.arrow="none"
   styleId="association"
   target.arrow="short"/>
  <EdgeStyle
   bend.style="angled"
   line.color="#000000"
   line.stroke="line_2"
   source.arrow="none"
   styleId="generalization"
   target.arrow="white_delta"/>
</StyleDefinition>

=== cloudgraph/cloudgraph/doclets/yworks-uml-doclet-3.0_01-jdk1.5/resources/styles/original-style.xml
<?xml version="1.0" encoding="UTF-8"?>
<StyleDefinition
 xmlns="http://www.yworks.com/xml/ydocstyle"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.yworks.com/xml/ydocstyle http://www.yworks.com/xml/schema/ydoc/1.0/ydocstyle.xsd">
  <NodeStyle
   styleId="node-type"
   shadow.color=""
   shadow.width="0"
   shadow.height="0"
   shadow.style="solid"
   line.color="#000000"
   line.stroke="line_1"
   header.fill.color=""
   header.gradient.color=""
   header.style="default"
   icon.style="ascii"
   section.fill.color=""
   section.gradient.color=""
   separator.fill.color=""
   separator.style="fixed"
   shape="rectangle"
   constraint.label.font="Dialog-plain-12"
   constraint.label.text=""
   constraint.label.text.color="#000000"
   name.label.font="Dialog-plain-12"
   name.label.text.color="#000000"
   stereotype.label.font="Dialog-plain-12"
   stereotype.label.text=""
   stereotype.label.text.color="#000000"
   type.label.font="Dialog-plain-12"
   type.label.text=""
   type.label.text.color="#000000"
   fields.fill.color=""
   fields.gradient.color=""
   fields.font="Dialog-plain-12"
   fields.text.color="#000000"
   constructors.fill.color=""
   constructors.gradient.color=""
   constructors.font="Dialog-plain-12"
   constructors.text.color="#000000"
   methods.fill.color=""
   methods.gradient.color=""
   methods.font="Dialog-plain-12"
   methods.text.color="#000000"/>
  <NodeStyle
   styleId="group"
   styleRef="node-type"
   line.color="#B2B2B2"
   header.fill.color="#FFFFFF"
   section.fill.color="#FFFFFF"/>
  <NodeStyle
   styleId="classifier"
   styleRef="node-type"
   separator.fill.color="#000000"/>
  <NodeStyle
   styleId="class"
   styleRef="classifier"
   line.color="#8282B2"
   header.fill.color="#BBBBFF"
   fields.fill.color="#BBBBFF"
   constructors.fill.color="#BBBBFF"
   methods.fill.color="#BBBBFF"/>
  <NodeStyle
   styleId="enum"
   styleRef="classifier"
   line.color="#7676B2"
   header.fill.color="#AAAAFF"
   fields.fill.color="#AAAAFF"
   constructors.fill.color="#AAAAFF"
   methods.fill.color="#AAAAFF"/>
  <NodeStyle
   styleId="error"
   styleRef="classifier"
   line.color="#6464B2"
   header.fill.color="#9191FF"
   fields.fill.color="#9191FF"
   constructors.fill.color="#9191FF"
   methods.fill.color="#9191FF"/>
  <NodeStyle
   styleId="enum.compact"
   styleRef="enum"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="class.detailed"
   styleRef="class"
   name.label.font="Dialog-bold-16"/>
  <NodeStyle
   styleId="abstract"
   styleRef="classifier"
   line.color="#8E8EB2"
   header.fill.color="#CCCCFF"
   fields.fill.color="#CCCCFF"
   constructors.fill.color="#CCCCFF"
   methods.fill.color="#CCCCFF"/>
  <NodeStyle
   styleId="error.detailed"
   styleRef="error"
   stereotype.label.text="&#171;error&#187;"
   name.label.font="Dialog-bold-16"/>
  <NodeStyle
   styleId="package"
   styleRef="node-type"
   line.color="#A6A6B2"
   header.fill.color="#EEEEFF"
   header.style="left_tab"
   section.fill.color="#EEEEFF"/>
  <NodeStyle
   styleId="class.compact"
   styleRef="class"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="annotation"
   styleRef="classifier"
   line.color="#9494B2"
   header.fill.color="#D5D5FF"
   section.fill.color="#D5D5FF"
   fields.fill.color="#D5D5FF"
   constructors.fill.color="#D5D5FF"
   methods.fill.color="#D5D5FF"/>
  <NodeStyle
   styleId="exception"
   styleRef="classifier"
   line.color="#6A6AB2"
   header.fill.color="#9999FF"
   fields.fill.color="#9999FF"
   constructors.fill.color="#9999FF"
   methods.fill.color="#9999FF"/>
  <NodeStyle
   styleId="abstract.compact"
   styleRef="abstract"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="enum.detailed"
   styleRef="enum"
   stereotype.label.text="&#171;enum&#187;"
   name.label.font="Dialog-bold-16"/>
  <NodeStyle
   styleId="interface"
   styleRef="classifier"
   line.color="#9A9AB2"
   header.fill.color="#DDDDFF"
   fields.fill.color="#DDDDFF"
   constructors.fill.color="#DDDDFF"
   methods.fill.color="#DDDDFF"
   constraint.label.font="Dialog-italic-12"
   name.label.font="Dialog-italic-12"
   type.label.font="Dialog-italic-12"/>
  <NodeStyle
   styleId="interface.detailed"
   styleRef="interface"
   stereotype.label.text="&#171;interface&#187;"
   name.label.font="Dialog-bolditalic-16"/>
  <NodeStyle
   styleId="error.compact"
   styleRef="error"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="exception.compact"
   styleRef="exception"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="annotation.compact"
   styleRef="annotation"
   shape="ellipse"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="annotation.detailed"
   styleRef="annotation"
   stereotype.label.text="&#171;annotation&#187;"
   name.label.font="Dialog-bold-16"/>
  <NodeStyle
   styleId="exception.detailed"
   styleRef="exception"
   stereotype.label.text="&#171;exception&#187;"
   name.label.font="Dialog-bold-16"/>
  <NodeStyle
   constraint.label.text="{abstract}"
   styleId="abstract.detailed"
   styleRef="abstract"
   name.label.font="Dialog-bold-16"/>
  <NodeStyle
   styleId="interface.compact"
   styleRef="interface"
   shape="ellipse"
   name.label.font="Dialog-bolditalic-13"/>
  <EdgeStyle
   styleId="relationship"
   line.color="#000000"
   line.stroke="line_1"
   bend.style="angled"
   source.arrow="none"
   target.arrow="none"/>
  <EdgeStyle
   styleId="realization"
   styleRef="relationship"
   line.stroke="dashed_1"
   target.arrow="white_delta"/>
  <EdgeStyle
   styleId="generalization"
   styleRef="relationship"
   target.arrow="white_delta"/>
  <EdgeStyle
   styleId="association"
   styleRef="relationship"
   target.arrow="UML:Wedge"/>
  <EdgeStyle
   styleId="dependency"
   styleRef="relationship"
   line.stroke="dashed_1"
   target.arrow="UML:Wedge"/>
</StyleDefinition>

=== cloudgraph/cloudgraph/doclets/yworks-uml-doclet-3.0_01-jdk1.5/resources/styles/default-style.xml
<?xml version="1.0" encoding="UTF-8"?>
<StyleDefinition
 xmlns="http://www.yworks.com/xml/ydocstyle"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.yworks.com/xml/ydocstyle http://www.yworks.com/xml/schema/ydoc/1.0/ydocstyle.xsd">
  <NodeStyle
   styleId="node-type"
   shadow.color=""
   shadow.width="0"
   shadow.height="0"
   shadow.style="solid"
   line.color="#000000"
   line.stroke="line_1"
   header.fill.color="#FFFFFF"
   header.gradient.color=""
   header.style="default"
   icon.style="ascii"
   separator.fill.color=""
   separator.style="fixed"
   shape="rectangle"
   section.fill.color="#FFFFFF"
   section.gradient.color=""
   constraint.label.font="Dialog-plain-12"
   constraint.label.text=""
   constraint.label.text.color="#000000"
   name.label.font="Dialog-bold-14"
   name.label.text.color="#000000"
   stereotype.label.font="Dialog-plain-12"
   stereotype.label.text=""
   stereotype.label.text.color="#000000"
   type.label.font="Dialog-plain-12"
   type.label.text=""
   type.label.text.color="#000000"
   fields.fill.color=""
   fields.gradient.color=""
   fields.font="Dialog-plain-12"
   fields.text.color="#000000"
   constructors.fill.color=""
   constructors.gradient.color=""
   constructors.font="Dialog-plain-12"
   constructors.text.color="#000000"
   methods.fill.color=""
   methods.gradient.color=""
   methods.font="Dialog-plain-12"
   methods.text.color="#000000"/>
  <NodeStyle
   styleId="group"
   styleRef="node-type"
   header.style="span_section"/>
  <NodeStyle
   styleId="classifier"
   styleRef="node-type"
   section.fill.color="#F3F3F3"
   separator.fill.color="#606060"/>
  <NodeStyle
   styleId="enum"
   styleRef="classifier"/>
  <NodeStyle
   styleId="error"
   styleRef="classifier"/>
  <NodeStyle
   styleId="enum.compact"
   styleRef="enum"/>
  <NodeStyle
   styleId="abstract"
   styleRef="classifier"/>
  <NodeStyle
   styleId="error.detailed"
   styleRef="error"/>
  <NodeStyle
   styleId="package"
   styleRef="node-type"
   header.style="left_tab"/>
  <NodeStyle
   styleId="annotation"
   styleRef="classifier"/>
  <NodeStyle
   styleId="exception"
   styleRef="classifier"/>
  <NodeStyle
   styleId="enum.detailed"
   styleRef="enum"/>
  <NodeStyle
   styleId="abstract.compact"
   styleRef="abstract"/>
  <NodeStyle
   styleId="interface"
   styleRef="classifier"/>
  <NodeStyle
   styleId="interface.detailed"
   styleRef="interface"/>
  <NodeStyle
   styleId="error.compact"
   styleRef="error"/>
  <NodeStyle
   styleId="exception.compact"
   styleRef="exception"/>
  <NodeStyle
   styleId="annotation.compact"
   styleRef="annotation"/>
  <NodeStyle
   styleId="class"
   styleRef="classifier"/>
  <NodeStyle
   styleId="annotation.detailed"
   styleRef="annotation"/>
  <NodeStyle
   styleId="exception.detailed"
   styleRef="exception"/>
  <NodeStyle
   styleId="abstract.detailed"
   styleRef="abstract"/>
  <NodeStyle
   styleId="class.detailed"
   styleRef="class"/>
  <NodeStyle
   styleId="interface.compact"
   styleRef="interface"/>
  <NodeStyle
   styleId="class.compact"
   styleRef="class"/>
  <EdgeStyle
   styleId="relationship"
   line.color="#000000"
   line.stroke="line_1"
   bend.style="angled"
   source.arrow="none"
   target.arrow="none"/>
  <EdgeStyle
   styleId="realization"
   styleRef="relationship"
   line.stroke="dashed_1"
   target.arrow="white_delta"/>
  <EdgeStyle
   styleId="generalization"
   styleRef="relationship"
   target.arrow="white_delta"/>
  <EdgeStyle
   styleId="association"
   styleRef="relationship"/>
  <EdgeStyle
   styleId="dependency"
   styleRef="relationship"
   line.stroke="dashed_1"
   source.arrow="none"
   target.arrow="UML:Wedge"/>
</StyleDefinition>
