=== cloudgraph/cloudgraph/doclets/yworks-uml-doclet-3.0_01-jdk1.5/resources/styles/ydocstyle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.yworks.com/xml/ydocstyle"
    xmlns="http://www.yworks.com/xml/ydocstyle"
    elementFormDefault="qualified">

    <xs:simpleType name="arrowType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="circle"/>
            <xs:enumeration value="transparent_circle"/>
            <xs:enumeration value="transparent_semi_circle"/>
            <xs:enumeration value="white_circle"/>
            
            <xs:enumeration value="uml"/>
            <xs:enumeration value="none"/>
            <xs:enumeration value="short"/>
            <xs:enumeration value="standard"/>
            
            <xs:enumeration value="delta"/>
            <xs:enumeration value="white_delta"/>
            <xs:enumeration value="diamond"/>
            <xs:enumeration value="white_diamond"/>
        </xs:restriction>
    </xs:simpleType>
 
    <xs:simpleType name="colorType">
        <xs:restriction base="xs:string">
            <xs:pattern value="#[a-f0-9]{6}|#[a-f0-9]{8}|"/>
        </xs:restriction>
    </xs:simpleType>
 
    <xs:simpleType name="fontType">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*-(bold|italic|bolditalic|plain)-[1-9]*"/>
        </xs:restriction>
    </xs:simpleType>
 
    <xs:simpleType name="lineType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(dashed|dotted|line)_[1-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:attributeGroup name="edgeStyleAttributes">
        <xs:attribute
            name="source.arrow"
            type="arrowType"
            use="optional"/>
        <xs:attribute
            name="target.arrow"
            type="arrowType"
            use="optional"/>
        
        <xs:attribute
            name="line.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="line.stroke" 
            type="lineType"
            use="optional"/>

         <xs:attribute
             name="bend.style"
             use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="angled"/>
                    <xs:enumeration value="smooth"/>
                </xs:restriction>
              </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>

    <xs:attributeGroup name="nodeStyleAttributes">
        <xs:attribute
            name="shadow.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="shadow.width" 
            type="xs:byte"
            use="optional"/>
        <xs:attribute
            name="shadow.height" 
            type="xs:byte"
            use="optional"/>
        <xs:attribute
            name="shadow.style"
            use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="solid"/>
                    <xs:enumeration value="soft"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute
            name="line.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="line.stroke"
            type="lineType"
            use="optional"/>
        
        <xs:attribute name="header.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="header.gradient.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="header.style"
            use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="default"/>
                    <xs:enumeration value="iconified"/>
                    <xs:enumeration value="span_section"/>
                    <xs:enumeration value="left_tab"/>
                    <xs:enumeration value="center_tab"/>
                    <xs:enumeration value="right_tab"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute
            name="icon.style"
            use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="vectorgraphics"/>
                    <xs:enumeration value="ascii"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute
            name="separator.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="separator.style"
            use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="dynamic"/>
                    <xs:enumeration value="fixed"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute
            name="shape"
            use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="ellipse"/>
                    <xs:enumeration value="oval"/>
                    <xs:enumeration value="circle"/>
                    <xs:enumeration value="rectangle"/>
                    <xs:enumeration value="triangle"/>
                    <xs:enumeration value="parallelogram"/>
                    <xs:enumeration value="hexagon"/>
                    <xs:enumeration value="diamond"/>
                    <xs:enumeration value="octagon"/>
                    <xs:enumeration value="roundrectangle"/>
                    <xs:enumeration value="rectangle3d"/>
                    <xs:enumeration value="trapezoid"/>
                    <xs:enumeration value="trapezoid2"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute
            name="section.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="section.gradient.color"
            type="colorType"
            use="optional"/>
        
        <xs:attribute
            name="constraint.label.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="constraint.label.text"
            type="xs:string"
            use="optional"/>
        <xs:attribute
            name="constraint.label.text.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="name.label.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="name.label.text.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="stereotype.label.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="stereotype.label.text"
            type="xs:string"
            use="optional"/>
        <xs:attribute
            name="stereotype.label.text.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="type.label.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="type.label.text"
            type="xs:string"
            use="optional"/>
        <xs:attribute
            name="type.label.text.color"
            type="colorType"
            use="optional"/>

        <xs:attribute
            name="fields.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="fields.gradient.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="fields.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="fields.text.color"
            type="colorType"
            use="optional"/>
        
        <xs:attribute
            name="constructors.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="constructors.gradient.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="constructors.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="constructors.text.color"
            type="colorType"
            use="optional"/>

        <xs:attribute
            name="methods.fill.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="methods.gradient.color"
            type="colorType"
            use="optional"/>
        <xs:attribute
            name="methods.font"
            type="fontType"
            use="optional"/>
        <xs:attribute
            name="methods.text.color"
            type="colorType"
            use="optional"/>
    </xs:attributeGroup>
 

    <xs:complexType name="nodeStyleType">
        <xs:attribute
            name="styleRef"
            type="xs:string"
            use="optional"/>
        <xs:attributeGroup ref="nodeStyleAttributes"/>
    </xs:complexType>

    <xs:element name="StyleDefinition">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="EdgeStyle">
                        <xs:complexType>
                            <xs:attribute
                                name="styleId"
                                type="xs:string"
                                use="required"/>
                            <xs:attribute
                                name="styleRef"
                                type="xs:string"
                                use="optional"/>
                            <xs:attributeGroup ref="edgeStyleAttributes"/>
                        </xs:complexType>
                    </xs:element>
                    
                    <xs:element name="NodeStyle">
                        <xs:complexType>
                            <xs:complexContent>
                                <xs:extension base="nodeStyleType">
                                    <xs:attribute
                                        name="styleId"
                                        type="xs:string"
                                        use="required"/>
                                </xs:extension>
                            </xs:complexContent>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>              
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== cloudgraph/cloudgraph/doclets/yworks-uml-doclet-3.0_01-jdk1.5/resources/styles/theBlues-style.xml
<?xml version="1.0" encoding="UTF-8"?>
<StyleDefinition
 xmlns="http://www.yworks.com/xml/ydocstyle"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.yworks.com/xml/ydocstyle http://www.yworks.com/xml/schema/ydoc/1.0/ydocstyle.xsd">
  <NodeStyle
   styleId="node-type"
   shadow.color="#5B5B5B"
   shadow.width="3"
   shadow.height="3"
   shadow.style="solid"
   line.color="#000000"
   line.stroke="line_1"
   header.fill.color=""
   header.gradient.color=""
   header.style="default"
   icon.style="ascii"
   section.fill.color=""
   section.gradient.color=""
   separator.fill.color="#000000"
   separator.style="fixed"
   shape="roundrectangle"
   constraint.label.font="Dialog-plain-12"
   constraint.label.text=""
   constraint.label.text.color="#000000"
   name.label.font="Dialog-plain-12"
   name.label.text.color="#000000"
   stereotype.label.font="Dialog-plain-12"
   stereotype.label.text=""
   stereotype.label.text.color="#000000"
   type.label.font="Dialog-plain-12"
   type.label.text=""
   type.label.text.color="#000000"
   fields.fill.color=""
   fields.gradient.color=""
   fields.font="Dialog-plain-12"
   fields.text.color="#000000"
   constructors.fill.color=""
   constructors.gradient.color=""
   constructors.font="Dialog-plain-12"
   constructors.text.color="#000000"
   methods.fill.color=""
   methods.gradient.color=""
   methods.font="Dialog-plain-12"
   methods.text.color="#000000"/>
  <NodeStyle
   styleId="group-type"
   styleRef="node-type"
   constraint.label.text.color="#404040"
   name.label.text.color="#404040"
   stereotype.label.text.color="#404040"
   type.label.text.color="#404040"/>
  <NodeStyle
   styleId="group"
   styleRef="group-type"
   header.fill.color="#E6EFFF"
   section.fill.color="#E6EFFF"/>
  <NodeStyle
   styleId="classifier"
   styleRef="node-type"/>
  <NodeStyle
   styleId="abstract"
   styleRef="classifier"
   header.fill.color="#3E7DBC"
   constraint.label.text.color="#C0C0C0"
   name.label.text.color="#C0C0C0"
   stereotype.label.text.color="#C0C0C0"
   type.label.text.color="#C0C0C0"
   fields.fill.color="#3E7DBC"
   fields.text.color="#C0C0C0"
   constructors.fill.color="#3E7DBC"
   constructors.text.color="#C0C0C0"
   methods.fill.color="#3E7DBC"
   methods.text.color="#C0C0C0"/>
  <NodeStyle
   styleId="interface-type"
   styleRef="classifier"
   header.fill.color="#89B5FB"
   constraint.label.text.color="#404040"
   name.label.text.color="#404040"
   stereotype.label.text.color="#404040"
   type.label.text.color="#404040"
   fields.fill.color="#89B5FB"
   fields.text.color="#404040"
   constructors.fill.color="#89B5FB"
   constructors.text.color="#404040"
   methods.fill.color="#89B5FB"
   methods.text.color="#404040"/>
  <NodeStyle
   styleId="package"
   styleRef="group-type"
   header.fill.color="#BFD8FF"
   header.style="left_tab"
   section.fill.color="#BFD8FF"/>
  <NodeStyle
   styleId="class-type"
   styleRef="classifier"
   header.fill.color="#0053A6"
   section.fill.color="#0053A6"
   constraint.label.text.color="#C0C0C0"
   name.label.text.color="#C0C0C0"
   stereotype.label.text.color="#C0C0C0"
   type.label.text.color="#C0C0C0"
   fields.fill.color="#0053A6"
   fields.text.color="#C0C0C0"
   constructors.fill.color="#0053A6"
   constructors.text.color="#C0C0C0"
   methods.fill.color="#0053A6"
   methods.text.color="#C0C0C0"/>
  <NodeStyle
   styleId="annotation"
   styleRef="interface-type"/>
  <NodeStyle
   styleId="abstract.compact"
   styleRef="abstract"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="exception"
   styleRef="class-type"/>
  <NodeStyle
   styleId="interface"
   styleRef="interface-type"
   constraint.label.font="Dialog-italic-12"
   name.label.font="Dialog-italic-12"
   type.label.font="Dialog-italic-12"/>
  <NodeStyle
   styleId="interface.detailed"
   styleRef="interface"
   name.label.font="Dialog-bolditalic-16"
   stereotype.label.text="«interface»"/>
  <NodeStyle
   styleId="exception.compact"
   styleRef="exception"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="annotation.compact"
   styleRef="annotation"
   shape="ellipse"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="annotation.detailed"
   styleRef="annotation"
   name.label.font="Dialog-bold-16"
   stereotype.label.text="«annotation»"/>
  <NodeStyle
   styleId="class"
   styleRef="class-type"/>
  <NodeStyle
   styleId="exception.detailed"
   styleRef="exception"
   name.label.font="Dialog-bold-16"
   stereotype.label.text="«exception»"/>
  <NodeStyle
   styleId="enum"
   styleRef="class-type"/>
  <NodeStyle
   styleId="abstract.detailed"
   styleRef="abstract"
   constraint.label.text="{abstract}"
   name.label.font="Dialog-bold-16"/>
  <NodeStyle
   styleId="enum.compact"
   styleRef="enum"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="error"
   styleRef="class-type"/>
  <NodeStyle
   styleId="class.detailed"
   styleRef="class"
   name.label.font="Dialog-bold-16"/>
  <NodeStyle
   styleId="error.detailed"
   styleRef="error"
   name.label.font="Dialog-bold-16"
   stereotype.label.text="«error»"/>
  <NodeStyle
   styleId="interface.compact"
   styleRef="interface"
   shape="ellipse"
   name.label.font="Dialog-bolditalic-13"/>
  <NodeStyle
   styleId="class.compact"
   styleRef="class"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="enum.detailed"
   styleRef="enum"
   name.label.font="Dialog-bold-16"
   stereotype.label.text="«enum»"/>
  <NodeStyle
   styleId="error.compact"
   styleRef="error"
   name.label.font="Dialog-bold-13"/>
  <EdgeStyle
   styleId="relationship"
   line.color="#000000"
   line.stroke="line_1"
   bend.style="smooth"
   source.arrow="none"
   target.arrow="none"/>
  <EdgeStyle
   styleId="realization"
   styleRef="relationship"
   line.stroke="dashed_1"
   target.arrow="white_delta"/>
  <EdgeStyle
   styleId="generalization"
   styleRef="relationship"
   target.arrow="white_delta"/>
  <EdgeStyle
   styleId="association"
   styleRef="relationship"
   target.arrow="UML:Wedge"/>
  <EdgeStyle
   styleId="dependency"
   styleRef="relationship"
   line.stroke="dashed_1"
   target.arrow="UML:Wedge"/>
</StyleDefinition>

=== cloudgraph/cloudgraph/doclets/yworks-uml-doclet-3.0_01-jdk1.5/resources/styles/dark-matter-style.xml
<?xml version="1.0" encoding="UTF-8"?>
<StyleDefinition
 xmlns="http://www.yworks.com/xml/ydocstyle"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.yworks.com/xml/ydocstyle http://www.yworks.com/xml/schema/ydoc/1.0/ydocstyle.xsd">
  <NodeStyle
   styleId="node-type"
   shadow.color=""
   shadow.width="0"
   shadow.height="0"
   shadow.style="solid"
   line.color="#000000"
   line.stroke="line_1"
   header.fill.color="#000000"
   header.gradient.color=""
   header.style="default"
   icon.style="ascii"
   separator.fill.color=""
   separator.style="fixed"
   shape="rectangle"
   section.fill.color=""
   section.gradient.color=""
   constraint.label.font="Dialog-plain-12"
   constraint.label.text=""
   constraint.label.text.color="#FFFFFF"
   name.label.font="Dialog-bold-12"
   name.label.text.color="#FFFFFF"
   stereotype.label.font="Dialog-bold-12"
   stereotype.label.text=""
   stereotype.label.text.color="#FFFFFF"
   type.label.font="Dialog-bold-12"
   type.label.text=""
   type.label.text.color="#FFFFFF"
   fields.fill.color=""
   fields.gradient.color=""
   fields.font="Dialog-bold-12"
   fields.text.color="#FFFFFF"
   constructors.fill.color=""
   constructors.gradient.color=""
   constructors.font="Dialog-bold-12"
   constructors.text.color="#FFFFFF"
   methods.fill.color="#CCCCCC"
   methods.gradient.color=""
   methods.font="Dialog-bold-12"
   methods.text.color="#FFFFFF"/>
  <NodeStyle
   styleId="group"
   styleRef="node-type"
   line.color="#B2B2B2"
   header.fill.color="#FFFFFF"
   separator.style="dynamic"
   shape="roundrectangle"
   section.fill.color="#FFFFFF"/>
  <NodeStyle
   styleId="classifier"
   styleRef="node-type"
   line.color="#6FA9FF"
   header.fill.color="#6EA9FF"
   header.gradient.color="#000000"
   header.style="default"
   icon.style="vectorgraphics"
   separator.fill.color="#000000"
   shape="roundrectangle"
   constraint.label.font="Dialog-bold-12"
   fields.fill.color="#666666"
   fields.gradient.color="#000000"
   constructors.fill.color="#666666"
   constructors.gradient.color="#000000"
   methods.fill.color="#666666"
   methods.gradient.color="#000000"/>
  <NodeStyle
   styleId="package"
   styleRef="node-type"
   line.color="#6EA9FF"
   header.fill.color="#000000"
   header.style="left_tab"
   separator.style="dynamic"
   shape="roundrectangle"
   section.fill.color="#333333"/>
  <NodeStyle
   styleId="compact"
   styleRef="classifier"
   header.fill.color="#666666"
   header.style="iconified"
   name.label.font="Dialog-bold-13"/>
  <NodeStyle
   styleId="interface.compact"
   styleRef="compact"
   line.color="#669900"
   shape="ellipse"/>
  <NodeStyle
   styleId="detailed"
   styleRef="classifier"
   name.label.font="Dialog-bold-16"/>
  <NodeStyle
   styleId="class.compact"
   styleRef="compact"/>
  <NodeStyle
   styleId="abstract.compact"
   styleRef="compact"/>
  <NodeStyle
   styleId="enum.detailed"
   styleRef="detailed"
   stereotype.label.text="«enum»"/>
  <NodeStyle
   styleId="interface.detailed"
   styleRef="detailed"
   header.fill.color="#6EA9FF"
   stereotype.label.text="«interface»"/>
  <NodeStyle
   styleId="error.compact"
   styleRef="compact"
   line.color="#CC0000"/>
  <NodeStyle
   styleId="exception.compact"
   styleRef="compact"
   line.color="#CC0000"/>
  <NodeStyle
   styleId="annotation.compact"
   styleRef="compact"
   line.color="#669900"
   shape="ellipse"/>
  <NodeStyle
   styleId="annotation.detailed"
   styleRef="detailed"
   stereotype.label.text="«annotation»"/>
  <NodeStyle
   styleId="exception.detailed"
   styleRef="detailed"
   stereotype.label.text="«exception»"/>
  <NodeStyle
   styleId="abstract.detailed"
   styleRef="detailed"
   constraint.label.text="{abstract}"/>
  <NodeStyle
   styleId="enum.compact"
   styleRef="compact"/>
  <NodeStyle
   styleId="class.detailed"
   styleRef="detailed"/>
  <NodeStyle
   styleId="error.detailed"
   styleRef="detailed"
   stereotype.label.text="«error»"/>
  <EdgeStyle
   styleId="relationship"
   line.color="#999999"
   line.stroke="line_1"
   bend.style="angled"
   source.arrow="none"
   target.arrow="none"/>
  <EdgeStyle
   styleId="realization"
   styleRef="relationship"
   line.stroke="dashed_1"
   target.arrow="white_delta"/>
  <EdgeStyle
   styleId="generalization"
   styleRef="relationship"
   target.arrow="white_delta"/>
  <EdgeStyle
   styleId="association"
   styleRef="relationship"
   target.arrow="UML:Wedge"/>
  <EdgeStyle
   styleId="dependency"
   styleRef="relationship"
   line.stroke="dashed_1"
   target.arrow="UML:Wedge"/>
</StyleDefinition>
